arch: amd64
cores: 1
features: nesting=1
hostname: OOB-Gateway
memory: 512
net0: name=eth0,bridge=vmbr0,gw=192.168.50.1,hwaddr=BC:24:11:14:E3:C7,ip=192.168.50.50/24,type=veth
onboot: 1
ostype: alpine
rootfs: local-lvm:vm-101-disk-0,size=4G
swap: 512
tags: gate
unprivileged: 1
lxc.cgroup2.devices.allow: c 10:200 rwm
lxc.mount.entry: /dev/net dev/net none bind,create=dir